version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - .:/workspace
    ports:
      - '8000:8000'
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  flutter:
    build:
      context: .
      dockerfile: flutter.Dockerfile
    volumes:
      - .:/workspace
    tty: true
