name: Export OpenAPI

on:
  push:
    paths:
      - backend/**
      - .github/workflows/export-openapi.yml

jobs:
  export-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Start FastAPI in background
        env:
          ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
        run: |
          cd backend
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Download OpenAPI spec
        run: |
          mkdir -p open-api
          curl http://localhost:8000/openapi.json -o open-api/tourplanning_openapi.json


      - name: Install OpenAPI Generator
        run: |
          npm install @openapitools/openapi-generator-cli -g

      - name: Generate Flutter API client
        run: |
          rm -rf ./mobile/openapi
          cd open-api
          openapi-generator-cli generate -g dart -i ./tourplanning_openapi.json -o ../mobile/openapi
          rm ../mobile/openapi/analysis_options.yaml
      
      - name: Commit OpenAPI spec
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add open-api/tourplanning_openapi.json
          git add mobile/openapi
          git commit -m "Update OpenAPI spec and generated Flutter client" || echo "No changes"
          git push
